version: "3.4"

services:
  hostmanage-inbox:
    image: managesio-web-api
    build:
      context: .
      dockerfile: Managesio.WebApi/Dockerfile
      network: host
      args:
        BUILD_VERSION: ${ASSEMBLY_VERSION-0.0.0.1}
    ports:
      - 5050:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
